// Mock Data for initial design phase
// Represents the actual JSON payload we will get from Python scrapers
const mockArticles = [
    {
        id: "a1b2c3d4",
        title: "OpenAI announces new reasoning models that can 'think' before answering",
        source: "The AI Rundown",
        url: "#",
        published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        summary: "OpenAI has officially released its new o1 series of AI models, designed to spend more time thinking through complex problems before responding, marking a significant leap in reasoning capabilities."
    },
    {
        id: "e5f6g7h8",
        title: "Apple Intelligence features arriving in October",
        source: "Ben Bites",
        url: "#",
        published_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        summary: "Apple confirmed that the first set of Apple Intelligence features will be available in beta next month as part of iOS 18.1, iPadOS 18.1, and macOS Sequoia 15.1."
    },
    {
        id: "i9j0k1l2",
        title: "I built an entire SaaS using only Claude Sonnet 3.5. Here is what I learned.",
        source: "Reddit",
        url: "#",
        published_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        summary: "A deep dive into the practical realities, limitations, and incredible speed of using modern LLMs for full-stack development without writing core logic yourself."
    },
    {
        id: "m3n4o5p6",
        title: "Google expands Gemini context window to 2 Million tokens",
        source: "The AI Rundown",
        url: "#",
        published_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        summary: "Google announced a massive upgrade to Gemini Pro 1.5, doubling its context window, allowing it to process massive codebases, long videos, and hundreds of documents at once."
    },
    {
        id: "q7r8s9t0",
        title: "NVIDIA's new Blackwell chips delayed due to design flaw",
        source: "Ben Bites",
        url: "#",
        published_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
        summary: "Production of NVIDIA's next-generation AI chips has hit a snag, potentially delaying shipments to major cloud providers by several months."
    }
];

// State Management
let articles = [];
let savedArticleIds = new Set();
let currentFilter = 'all';

// Initialize Application
document.addEventListener('DOMContentLoaded', () => {
    loadSavedArticles();
    loadArticlesData(); // Will be replaced by actual fetch later
    setupEventListeners();
    renderArticles();
});

function loadSavedArticles() {
    const saved = localStorage.getItem('scraperrr_saved_articles');
    if (saved) {
        try {
            const parsed = JSON.parse(saved);
            savedArticleIds = new Set(parsed);
        } catch (e) {
            console.error("Failed to parse saved articles", e);
        }
    }
}

function saveToLocalStorage() {
    localStorage.setItem('scraperrr_saved_articles', JSON.stringify([...savedArticleIds]));
}

function loadArticlesData() {
    // In actual implementation, we will fetch from backend or JSON generated by scraper
    // For now, use mock data mapped exactly to our gemini.md schema.
    articles = [...mockArticles];
}

function setupEventListeners() {
    // Navigation Filters
    const navButtons = document.querySelectorAll('.nav-btn');
    navButtons.forEach(btn => {
        btn.addEventListener('click', (e) => {
            navButtons.forEach(b => b.classList.remove('active'));
            e.currentTarget.classList.add('active');
            currentFilter = e.currentTarget.getAttribute('data-filter');
            
            // Update Header
            const titleEl = document.getElementById('page-title');
            if(currentFilter === 'all') titleEl.textContent = 'Latest Updates';
            else if(currentFilter === 'saved') titleEl.textContent = 'Saved Articles';
            else if(currentFilter === 'benbites') titleEl.textContent = 'Ben Bites';
            else if(currentFilter === 'airundown') titleEl.textContent = 'The AI Rundown';
            else if(currentFilter === 'reddit') titleEl.textContent = 'Reddit Tracker';

            renderArticles();
        });
    });

    // Refresh Button
    document.getElementById('refresh-btn').addEventListener('click', () => {
        const icon = document.querySelector('#refresh-btn i');
        icon.classList.add('fa-spin');
        setTimeout(() => {
            icon.classList.remove('fa-spin');
            renderArticles();
        }, 800);
    });
}

function toggleSaveArticle(id, event) {
    event.preventDefault(); 
    if (savedArticleIds.has(id)) {
        savedArticleIds.delete(id);
    } else {
        savedArticleIds.add(id);
    }
    saveToLocalStorage();
    
    // UI reactive update
    if (currentFilter === 'saved') {
        renderArticles();
    } else {
        const btn = document.querySelector(`button[data-id="${id}"]`);
        if(btn) {
            btn.classList.toggle('saved');
            btn.innerHTML = savedArticleIds.has(id) ? '<i class="fa-solid fa-bookmark"></i>' : '<i class="fa-regular fa-bookmark"></i>';
        }
    }
}

// Ensure function is available globally for inline onclick
window.toggleSaveArticle = toggleSaveArticle;

function formatTimeAgo(dateString) {
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now - date;
    const diffHrs = Math.floor(diffMs / (1000 * 60 * 60));
    
    if (diffHrs < 1) {
        const diffMins = Math.floor(diffMs / (1000 * 60));
        return `${diffMins}m ago`;
    }
    return `${diffHrs}h ago`;
}

function getSourceClass(source) {
    if (source.includes('Ben Bites')) return 'source-benbites';
    if (source.includes('AI Rundown')) return 'source-airundown';
    if (source.includes('Reddit')) return 'source-reddit';
    return '';
}

function renderArticles() {
    const container = document.getElementById('articles-container');
    container.innerHTML = '';

    let filtered = articles;

    if (currentFilter === 'saved') {
        filtered = articles.filter(a => savedArticleIds.has(a.id));
    } else if (currentFilter === 'benbites') {
        filtered = articles.filter(a => a.source.includes('Ben Bites'));
    } else if (currentFilter === 'airundown') {
        filtered = articles.filter(a => a.source.includes('AI Rundown'));
    } else if (currentFilter === 'reddit') {
        filtered = articles.filter(a => a.source.includes('Reddit'));
    }

    if (filtered.length === 0) {
        container.innerHTML = `
            <div style="grid-column: 1 / -1; text-align: center; padding: 4rem; color: var(--text-secondary);">
                <i class="fa-regular fa-folder-open" style="font-size: 3rem; margin-bottom: 1rem; opacity: 0.5;"></i>
                <p>No articles found for this view.</p>
            </div>
        `;
        return;
    }

    filtered.forEach((article, index) => {
        const isSaved = savedArticleIds.has(article.id);
        const card = document.createElement('div');
        card.className = 'article-card';
        card.style.animationDelay = `${index * 0.05}s`; 
        
        card.innerHTML = `
            <div class="article-meta">
                <span class="source-badge ${getSourceClass(article.source)}">${article.source}</span>
                <span class="publish-time"><i class="fa-regular fa-clock"></i> ${formatTimeAgo(article.published_at)}</span>
            </div>
            <h3 class="article-title">${article.title}</h3>
            <p class="article-summary">${article.summary}</p>
            <div class="article-footer">
                <a href="${article.url}" class="read-more" target="_blank">Read Article <i class="fa-solid fa-arrow-right"></i></a>
                <button class="save-btn ${isSaved ? 'saved' : ''}" data-id="${article.id}" onclick="toggleSaveArticle('${article.id}', event)">
                    <i class="fa-${isSaved ? 'solid' : 'regular'} fa-bookmark"></i>
                </button>
            </div>
        `;
        container.appendChild(card);
    });
}
